version: '3.7'


volumes:
  postgres_data:

services:
  api:
    build: .
    command: npm run start
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/data/db
